[package]
name = "range-set-int"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
rand = "0.8.5"
thousands = "0.2.0"
itertools = "0.10.1"
num-integer = "0.1.44"
num-traits = "0.2.14"
gen_ops = "0.2.0"
thiserror = "1.0"

[dev-dependencies]
syntactic-for = "0.1.1"
criterion = "0.4.0"
maplit = "1.0.2"
trybuild = "1.0.53"

[[bench]]
name = "bench"
harness = false

[profile.release]
debug = true
