[package]
name = "range-set-int"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
rand = "0.8.5"
thousands = "0.2.0"
itertools = "0.10.1"
num-integer = "0.1.44"
num-traits = "0.2.14"
trait-set = "0.3.0"
gen_ops = "0.2.0"
sorted-iter = "0.1.8"
dyn-clone = "1.0.10"
maplit = "1.0.2"

[dev-dependencies]
syntactic-for = "0.1.1"
criterion = "0.4.0"
# pprof = { version = "0.11.0", features = ["flamegraph", "criterion"] }

[[bench]]
name = "bench"
harness = false

[profile.release]
debug = true
