[package]
name = "range-set-int"
version = "0.1.0"
edition = "2021"

[workspace]

members = [".", "tests_common"]
[lib]

[dependencies]
itertools = "0.10.1"
num-integer = "0.1.44"
num-traits = "0.2.14"
gen_ops = "0.2.0"
thiserror = "1.0"
rand = "0.8.4"

[dev-dependencies]
tests_common = { path = "tests_common" }
syntactic-for = "0.1.1"
criterion = { version = "0.4", features = ["html_reports"] }
trybuild = "1.0.53"
thousands = "0.2.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
rangemap = "1.3.0"


# Declare a benchmark called ""bench" without the standard benchmarking harness. 
[[bench]]
name = "bench"
harness = false

[profile.release]
debug = true
